'''
How many distinct terms are in the sequence generated by a**b for 2 <= a <= 100 and 2 <= b <= 100?

if k | b then  a**b == (a**k)**b/k . These are the dups. 
One could use the number of divisiors of b to compute this but the brute force is ok 0(n**2)
'''

s=set()

for a in xrange(2, 101):
    for b in xrange(2, 101):
        s.add(a**b)
print len(s)